ft(S3UTILS-46): Add DELETED_BEFORE option to cleanupNoncurrentVersions.js
scality/s3utils pull request #187
Opened 2022-01-26 23:19 UTC by tmacro

2022-01-26 23:19 UTC, bert-e commented
# Hello tmacro,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/s3utils/bert-e/doc/user).





*Status report is not available.*

2022-01-26 23:19 UTC, bert-e commented
# Incorrect fix version



The `Fix Version/s` in issue S3UTILS-46 contains:


* *None*



Considering where you are trying to merge, I ignored possible hotfix versions and I expected to find:



* `1.11.10`


Please check the `Fix Version/s` of S3UTILS-46, or the target
branch of this pull request.

2022-01-26 23:19 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers

2022-01-27 19:30 UTC, jonathan-gramain requested changes

2022-01-27 19:30 UTC, jonathan-gramain commented on cleanupNoncurrentVersions.js
> +            if (isDeleted && isElligible) {
This should be conditioned to the existence of the delete marker:

```suggestion
            const isEligible = isDeleted && _deleteMarkerIsEligible(
                deleteMarkers[matchingDeleteMarkerIndex].LastModified);

            if (isEligible) {
```

2022-01-27 19:30 UTC, jonathan-gramain commented on cleanupNoncurrentVersions.js
> +                if (!ONLY_DELETED || (isDeleted && isElligible)) {
minor spelling:

```suggestion
                const isEligible = _deleteMarkerIsEligible(lastCurrentDeleteMarker.LastModified);
                if (!ONLY_DELETED || (isDeleted && isEligible)) {
```

2022-01-27 19:30 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers






The following reviewers are expecting changes from the author, or must review again:

* @jonathan-gramain

2022-01-27 19:35 UTC, jonathan-gramain commented
@tmacro can you test this script with at least one object of each of the following:

- non-deleted object
- deleted object, more recently than DELETED_BEFORE
- deleted object, before DELETED_BEFORE

Also the script should be tested without the DELETED_BEFORE option, and with or without the ONLY_DELETED, on a deleted and non-deleted object, to check for possible regressions.

2022-01-28 00:36 UTC, jonathan-gramain approved these changes

2022-01-28 00:36 UTC, jonathan-gramain commented on cleanupNoncurrentVersions.js
> +            if (isDeleted && isEligible) {
Since `isEligible` implies `isDeleted` now:

```suggestion
            if (isEligible) {
```

2022-01-28 00:36 UTC, jonathan-gramain commented on cleanupNoncurrentVersions.js
> +                if (!ONLY_DELETED || (isDeleted && isEligible)) {
```suggestion
                if (!ONLY_DELETED || isEligible) {
```

2022-01-28 00:36 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers

2022-01-28 01:07 UTC, watsaqat approved these changes

2022-01-28 01:22 UTC, tmacro commented
/approve

2022-01-28 01:26 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/1.11`



The following branches will **NOT** be impacted:

* `development/1.10`
* `development/1.8`
* `development/1.9`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2022-01-28 01:26 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/1.11`



The following branches have **NOT** changed:

* `development/1.10`
* `development/1.8`
* `development/1.9`



Please check the status of the associated issue S3UTILS-46.

Goodbye tmacro.

2022-01-28 01:26 UTC, merged