ft: S3C-5190 continuous integrity check
scality/s3utils pull request #188
Opened 2022-01-27 03:14 UTC by vrancurel

Continuous integrity check based on the existing `compareBuckets` tool.

The tool maintains 2 sets of differences, and follow the oplog to update the sets in real-time.

It persists the state in ZK/RING to avoid rescanning the bucket each time, in using the snapshot/scan/ZK pattern.

2022-01-27 03:14 UTC, bert-e commented
# Hello vrancurel,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/s3utils/bert-e/doc/user).





*Status report is not available.*

2022-01-27 03:14 UTC, bert-e commented
# Incorrect Jira project



The Jira issue S3C-5190 specified in the source
branch name, does not belong to project `S3UTILS`.

2022-01-27 03:15 UTC, vrancurel commented
This is a WIP for now as some generic code (e.g. `SortedSet`) can be moved in Arsenal.

2022-02-04 02:11 UTC, vrancurel commented on compareBuckets/BucketdOplogInterface.js
> +        this.raftId = 2; // XXX use route
I will add a `getBucketRaftId()` method in `bucketclient`.

2022-02-04 02:12 UTC, vrancurel commented on compareBuckets/PersistRingInterface.js
> +        const spPath = '/proxy/DC1/'; // do not forget "/" at the end !!!
Those will be passed in env / params.

2022-02-04 02:12 UTC, vrancurel commented on compareBuckets/compareBuckets.js
> +        this.srcPersist = new PersistFileInterface();
For prod it will be using `PersistRingInterface()`

2022-02-04 02:14 UTC, vrancurel commented
Code complete: once overall code approved I will dispatch the generic code in Arsenal and do proper PRs with proper project names.

2022-02-04 20:11 UTC, miniscruff requested changes

2022-02-04 20:11 UTC, miniscruff commented on tests/unit/compareBuckets/Injector.js
> +        return result;
prando seems to have a next string method, maybe something like:
```suggestion
        const characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
        return this.rnd.nextString(len, characters);
```

2022-02-04 20:11 UTC, miniscruff commented on tests/unit/compareBuckets/Injector.js
> +    genBase16(len) {
same as above

2022-02-04 20:11 UTC, miniscruff commented on tests/unit/compareBuckets/Injector.js
> +    _zeroPad(s, n, width) {
```js
return s + n.toString().padStart(width, '0');
```
You can use padStart here I believe

2022-02-04 20:11 UTC, miniscruff commented on tests/unit/compareBuckets/Injector.js
> +        injectParams.suffix = suffix;
any reason to use the pattern of creating an empty object and filling it, over filling it when creating it? I have seen it a few times and not sure if there is a reason.

2022-02-04 20:11 UTC, miniscruff commented on tests/unit/compareBuckets/Injector.js
> +                    const idx = Math.floor(this.rnd.next() * inputKeys.length);
prando has a nextInt method: https://www.npmjs.com/package/prando

2022-02-04 20:11 UTC, miniscruff commented on compareBuckets/compareBuckets.js
> +            diffMgr.state[target].set(item.key, _value);
```suggestion
            const _value = {};
            Object.assign(_value, item.value);
            _value.mismatch = diffMgr.MismatchNoExist;
            const _value = Object.assign({}, item.value, { mismatch: dffMgr.MismatchNoExist });
            diffMgr.state[target].set(item.key, _value);
```

Or using spread:
```js
diffMgr.state[target].set(item.key, { ...item.value, mismatch: diffMgr.MismatchNoExist });
```

2022-02-04 20:11 UTC, miniscruff commented on compareBuckets/compareBuckets.js
> +            assert(value.mismatch === diffMgr.MismatchNoExist);
I would use assert.strictEqual instead of assert x === y, but also I think we want to not use asserts outside of tests.

2022-02-04 20:11 UTC, miniscruff commented on compareBuckets/PersistRingInterface.js
> +        async.waterfall([
instead of waterfall I think we should switch to using async/await if possible. Not sure how much work switching between the two are but something to consider.

2022-02-04 20:11 UTC, miniscruff commented on compareBuckets/PersistRingInterface.js
> +                        }
I think you can just do `!!doesExist` or something similar based on what stat is exactly, like maybe `stat !== undefined`.

2022-02-04 20:11 UTC, miniscruff commented on compareBuckets/PersistMemInterface.js
> +        return this.offsets[bucketName];
```suggestion
        return this.offsets[bucketName] || {};
```

2022-02-04 20:11 UTC, miniscruff commented on compareBuckets/MongoOplogInterface.js
> +    start(bucketName, persist, persistData, stopAt, cb) {
I really think we should split this function up and as stated before maybe switch to async/await. If not splitting use `function funcName` syntax over the anonymous array functions to provide context.

2022-02-04 20:11 UTC, miniscruff commented on compareBuckets/Flusher.js
> +            assert(false);
I would add a message to this assert at least, debugging would be very hard otherwise.

2022-02-04 20:11 UTC, miniscruff commented on compareBuckets/BucketdOplogInterface.js
> +    start(bucketName, persist, persistData, flusherParams, cb) {
Same as the other function, this is very long and has not that much context or docs.

2022-02-04 20:11 UTC, miniscruff commented on compareBuckets/BucketdOplogInterface.js
> + * Main interface for bucketd oplog management
Could maybe use jsdocs interface https://jsdoc.app/tags-interface.html or similar

2022-02-04 20:11 UTC, miniscruff commented on compareBuckets/ArrayUtils.js
> +symDiff(k1, k2, v1, v2, cb) {
```suggestion
function symDiff(k1, k2, v1, v2, cb) {
```

2022-02-06 03:18 UTC, vrancurel commented on tests/unit/compareBuckets/Injector.js
> +        return result;
Yes, did not see it. Prando is really cool because it can be seeded, so make hard bugs to find easily reproducible.

2022-10-06 16:39 UTC, closed without merging