imp: S3UTILS-101 improve stalled retry query
scality/s3utils pull request #258
Opened 2022-08-31 22:23 UTC by naren-rajendran

Remove regex filter on id and handle master key check on the client.

2022-08-31 22:23 UTC, bert-e commented
# Hello naren-rajendran,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://bert-e.scality.net/scality/s3utils/doc/user).





*Status report is not available.*

2022-08-31 22:23 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers

2022-09-01 01:38 UTC, rahulreddy requested changes

2022-09-01 01:38 UTC, rahulreddy commented on stalledRetry.yaml
> +              value: "primary"
Is there any reason you are targeting Primary?

2022-09-01 01:38 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers






The following reviewers are expecting changes from the author, or must review again:

* @rahulreddy

2022-09-01 01:47 UTC, naren-rajendran commented on stalledRetry.yaml
> +              value: "primary"
It was already forced to use `primary` https://github.com/scality/s3utils/pull/258/files#diff-9b354bcb233267c1a41c1bd8dd4cc82ddef2ae458fed06e07697237a420e98e4L85 that is why I wanted to have this as a variable.

2022-09-01 01:47 UTC, naren-rajendran commented on stalledRetry.yaml
> +              value: "primary"
This is only with stalled (not sure why), count items uses `secondaryPreferred`.

2022-09-01 01:51 UTC, rahulreddy commented on stalledRetry.yaml
> +              value: "primary"
Ok unless writes are needed you should go with secondary preferred

2022-09-01 02:02 UTC, naren-rajendran commented on stalledRetry.yaml
> +              value: "primary"
Modified.

2022-09-01 02:09 UTC, rahulreddy approved these changes

2022-09-01 02:09 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers

2022-09-01 02:14 UTC, miniscruff approved these changes

2022-09-01 02:39 UTC, naren-rajendran commented
/approve

2022-09-01 02:39 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/1.13`



The following branches will **NOT** be impacted:

* `development/1.12`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2022-09-01 02:40 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/1.13`



The following branches have **NOT** changed:

* `development/1.12`



Please check the status of the associated issue S3UTILS-101.

Goodbye naren-rajendran.

2022-09-01 02:40 UTC, merged