[S3UTILS-130] ✨ Implement GHAS
scality/s3utils pull request #287
Opened 2023-05-15 21:23 UTC by gaspardmoindrot

2023-05-15 21:23 UTC, bert-e commented
# Hello gaspardmoindrot,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://bert-e.scality.net/scality/s3utils/doc/user).





*Status report is not available.*

2023-05-15 21:23 UTC, bert-e commented
# Incorrect fix version



The `Fix Version/s` in issue S3UTILS-130 contains:


* *None*



Considering where you are trying to merge, I ignored possible hotfix versions and I expected to find:



* `1.13.20`


Please check the `Fix Version/s` of S3UTILS-130, or the target
branch of this pull request.

2023-05-15 21:24 UTC, gaspardmoindrot commented on .github/workflows/dependency-review.yaml
> +        uses: actions/dependency-review-action@v3
```suggestion
        uses: actions/dependency-review-action@v3

```

2023-05-15 21:24 UTC, gaspardmoindrot commented on .github/workflows/security.yaml
> +       registry: registry.scality.com
```suggestion
       registry: registry.scality.com

```

2023-05-15 23:09 UTC, tcarmet requested changes

2023-05-15 23:09 UTC, tcarmet commented on .github/workflows/security.yaml
> +       REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
The secrets are badly defined in the workflow, use this method instead:
```suggestion
     secrets: inherit
```

2023-05-16 18:17 UTC, tcarmet approved these changes

2023-05-16 18:17 UTC, bert-e commented
# Incorrect fix version



The `Fix Version/s` in issue S3UTILS-130 contains:


* *None*



Considering where you are trying to merge, I ignored possible hotfix versions and I expected to find:



* `1.13.21`


Please check the `Fix Version/s` of S3UTILS-130, or the target
branch of this pull request.

2023-05-18 21:32 UTC, gaspardmoindrot commented
`ping`

2023-05-18 21:32 UTC, bert-e commented
# Incorrect fix version



The `Fix Version/s` in issue S3UTILS-130 contains:


* `1.13.20`



Considering where you are trying to merge, I ignored possible hotfix versions and I expected to find:



* `1.13.21`


Please check the `Fix Version/s` of S3UTILS-130, or the target
branch of this pull request.

2023-05-18 22:30 UTC, gaspardmoindrot commented
`ping`

2023-05-18 22:30 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers

2023-05-23 22:01 UTC, tmacro approved these changes

2023-05-24 17:00 UTC, gaspardmoindrot commented
`ping`

2023-05-24 17:03 UTC, gaspardmoindrot commented
/approve

2023-05-24 17:04 UTC, bert-e commented
# Build failed



The build for [commit](https://github.com/scality/s3utils/commit/d2c7dccae69c33f586c54bd89b7ea1e560ff8d95) did not succeed in branch improvement/S3UTILS-130-implement-ghas.




*The following options are set:* **approve**

2023-05-24 19:14 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/1.13`



The following branches will **NOT** be impacted:

* `development/1.4`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2023-05-24 19:14 UTC, gaspardmoindrot commented
/approve

2023-05-24 19:27 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/1.13`



The following branches have **NOT** changed:

* `development/1.4`



Please check the status of the associated issue S3UTILS-130.

Goodbye gaspardmoindrot.

2023-05-24 19:28 UTC, merged