S3UTILS-145: Bump version
scality/s3utils pull request #297
Opened 2023-08-26 01:21 UTC by tmacro

2023-08-26 01:21 UTC, bert-e commented
# Hello tmacro,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://bert-e.scality.net/scality/s3utils/doc/user).





*Status report is not available.*

2023-08-26 01:21 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers

2023-08-26 10:01 UTC, francoisferrand requested changes, later dismissed
Why do you want to bump?

The 1.13.24 release is already made, on the exact commit of the bump: so no point making a new release now...

And it is best to bump at the time of release, so that git commit history is consistent with tags (ideally tag is on the bump commit), to avoid confusion and possibly skipping a version.

2023-08-26 10:01 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers






The following reviewers are expecting changes from the author, or must review again:

* @francoisferrand

2023-08-28 15:31 UTC, tmacro commented
So a few things seem to be going on. I'm trying to bump 1.14 and just bumped the last digit expecting the minor version to be "14".  I should have checked as we're terrible about updating those sorts of things.

2023-08-28 15:33 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers

2023-08-28 16:29 UTC, rachedbenmustapha approved these changes

2023-08-28 17:17 UTC, jonathan-gramain approved these changes

2023-08-28 17:18 UTC, tmacro commented
/approve

2023-08-28 17:18 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/1.14`



The following branches will **NOT** be impacted:

* `development/1.13`
* `development/1.4`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2023-08-28 17:18 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/1.14`



The following branches have **NOT** changed:

* `development/1.13`
* `development/1.4`



Please check the status of the associated issue S3UTILS-145.

Goodbye tmacro.

2023-08-28 17:18 UTC, merged